ModelParameters:
  bagging_fraction: 0.9406557405070085
  bagging_freq: 1
  feature_fraction: 0.9392667095011045
  lambda_l2: 0.8734764705707838
  learning_rate: 0.03
  max_depth: 10
  metric: binary_logloss
  min_data_in_leaf: 221
  nthread: -1
  num_class: 1
  num_leaves: 627
  objective: binary
  verbose: -1
Name: lightgbm
Normalization: false
OnehotEncoding: false
Standardization: false
