data_clear_flag: false
data_file_type: libsvm
dataset_name: plaindataset
dataset_weight: null
feature_configure_path: null
feature_generator_flag: false
increment_column_name_flag: false
init_folder_name: qrgBal
init_model_root: null
init_work_root: /home/liangqian/Gauss/experiments/qrgBal
loss_name: null
metric_eval_used_flag: false
metric_name: binary_f1
mode: udf
model_zoo:
- lightgbm
supervised_feature_selector_flag: true
supervised_selector_mode: topk_select
target_names: null
task_name: binary_classification
train_column_name_flag: false
train_data_path: "/home/liangqian/\u6587\u6863/\u516C\u5F00\u6570\u636E\u96C6/a9a/a9a.t"
unsupervised_feature_selector_flag: true
use_weight_flag: true
val_column_name_flag: false
val_data_path: "/home/liangqian/\u6587\u6863/\u516C\u5F00\u6570\u636E\u96C6/a9a/a9a.t"
weight_column_flag: false
weight_column_name: null
work_root: /home/liangqian/Gauss/experiments/UouyKZ
